services:
  web:
    build: .
    image: ghcr.io/tisat83/2pac:latest
    environment:
      - NODE_ENV=production
    ports:
      - "127.0.0.1:3005:3000"
    restart: unless-stopped
  nginx:
    image: nginx:alpine
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
